// Bindings come from `import { env } from "cloudflare:workers"` (adapter-cloudflare 8);
// see src/worker-configuration.d.ts, generated by `pnpm cf-typegen`.
declare global {
	namespace App {}
}

export {};
